name: solution-spike-stone
services:
  spike-stone:
    container_name: spike-stone    
    build:
      context: .
      dockerfile: Spike-Stone/Dockerfile
    ports:
      - "5000:8080"    
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    environment:
        MSSQL_SA_PASSWORD: "Stone@2024"
        ACCEPT_EULA: "Y"        