on:
  push:
    branches:
    - master
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: spike-stone-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: azure-container-stone
  RESOURCE_GROUP: spike-dev-rg
  CONTAINER_REGISTRY_NAME: registrystone
  CONTAINER_REGISTRY_LOGIN_SERVER: registrystone.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.azure_container_stone_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.registrystone_USERNAME_A1CA }}
        acrPassword: ${{ secrets.registrystone_PASSWORD_A1CA }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
