# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - spike-stone

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://registrystone.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_480e272c7f804debbdb2b12e0b46ec36 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e185a31e781e4e72b9dd4dbec2e1145e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registrystone.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_480e272c7f804debbdb2b12e0b46ec36 }}/teste:${{ github.sha }}
        file: ./Spike-Stone/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'spike-stone'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dd546cfdd04442668bbd8c033126adb6 }}
        images: 'registrystone.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_480e272c7f804debbdb2b12e0b46ec36 }}/teste:${{ github.sha }}'
