name: Deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: registrystone.azurecr.io
        username: ${{ secrets.SPIKESTONECONTAINERAPP_REGISTRY_USERNAME }}
        password: ${{ secrets.SPIKESTONECONTAINERAPP_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t registrystone.azurecr.io/spike-stone:latest .
        docker push registrystone.azurecr.io/spike-stone:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container App
      run: |
        az containerapp create \
          --name spike-stone-app \
          --resource-group spike-dev-rg \
          --image registrystone.azurecr.io/spike-stone:latest \
          --environment production \
          --cpu 0.5 \
          --memory 1.0Gi \
          --ingress external \
          --target-port 80

