name: Trigger auto deployment for spike-stone-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'Spike-Stone/Dockerfile    /**'
    - '.github/workflows/spike-stone-container-app-AutoDeployTrigger-679076b4-ffe9-4105-a374-d149fc824082.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPIKESTONECONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPIKESTONECONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPIKESTONECONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/Spike-Stone/Dockerfile     
          registryUrl: registrystone.azurecr.io
          registryUsername: ${{ secrets.SPIKESTONECONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPIKESTONECONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: spike-stone-container-app
          resourceGroup: spike-dev-rg
          imageToBuild: registrystone.azurecr.io/spike-stone-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


